---
deployment:
  tasks:
  
    - ./virtualenv/bin/pip install -r requirements.txt
    
    - ./virtualenv/bin/python cosmos/manage.py migrate
    
    - ./virtualenv/bin/python cosmos/manage.py collectstatic --noinput
    
    - touch /home/valucosmos/cosmos/cosmos/wsgi.py
