# Generated by Django 4.2.16 on 2024-10-02 12:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(help_text='Color debe ser hexadecimal (ejemplo: #FF5733).', max_length=7, validators=[django.core.validators.RegexValidator(message='El formato de color debe ser #RRGGBB (hexadecimal).', regex='^#[0-9a-fA-F]{6}$')])),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Uni',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('tipo', models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada')], default='publica', help_text='Selecciona si la universidad es pública o privada.', max_length=7)),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('modalidad', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField(help_text='Duración de la carrera en años (max 10)', validators=[django.core.validators.MaxValueValidator(10)])),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Costo mensual de la carrera (solo para universidades privadas).', max_digits=10, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_app.cat')),
                ('uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_app.uni')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
    ]
