# Generated by Django 4.2.16 on 2024-10-19 00:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('modalidad', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField(help_text='Duración de la carrera en años (max 10)', validators=[django.core.validators.MaxValueValidator(10)])),
                ('enroll', models.URLField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_app.cat')),
                ('uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_app.uni')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='UniImg',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default='Uni/default.jgp', upload_to='Uni')),
                ('uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_app.uni')),
            ],
        ),
        migrations.CreateModel(
            name='CursoImg',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default='Curso/default.jgp', upload_to='Curso')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_app.curso')),
            ],
        ),
    ]
