# Generated by Django 4.2.16 on 2024-10-28 19:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0002_curso_uniimg_cursoimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('mixta', 'Mixta'), ('virtual', 'Virtual')], default='presencial', max_length=50),
        ),
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(help_text='Color debe ser hexadecimal (ejemplo: #FF5733).', max_length=7, validators=[django.core.validators.RegexValidator(message="El formato de color debe ser #RRGGBB (hexadecimal, incluyendo el '#').", regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('mixta', 'Mixta'), ('virtual', 'Virtual')], default='presencial', max_length=50),
        ),
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enroll', models.URLField()),
                ('uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_app.uni')),
            ],
            options={
                'verbose_name': 'Beca',
                'verbose_name_plural': 'Becas',
            },
        ),
    ]
