# Generated by Django 4.2.16 on 2024-10-28 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0003_alter_curso_options_curso_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo mensual de la carrera (solo para universidades privadas).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duración del curso en meses (max 24)', validators=[django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
